### PR TITLE
Spread the word

### PR DESCRIPTION
**Pull request by zaridan**
- Add copy for Spread the word widget
- Create spread-the-word.html
- Add intro to spread-the-word page

### CODE REVIEW

**Comment by zaridan** [comment]
Hi @edswf1  - I did only a little bit of work here to dust off my old unused dev skills and be sure I'm doing things right.

I plan to work on one page of info at a time as I'm able. 

Please let me know if you prefer things done any differently, or have any input for content.

**Comment by edswf1** [comment]
> Hi @edswf1 - I did only a little bit of work here to dust off my old unused dev skills and be sure I'm doing things right.
> 
> I plan to work on one page of info at a time as I'm able.
> 
> Please let me know if you prefer things done any differently, or have any input for content.

Thank you, very nice. If you are struggling with filling a whole page -> imo there is no need for a single page for every widget, just the widget content itself will help a lot. As translation is needed for every content i would rather add pages in the aftermath and concentrate on the widget content for now.
I think the only two pages needed would be the one you created and a page about running a full node, but to keep this PR simple i would only go for widget content now.

Edit: to keep it isolated could create your PR for the support-dogecoin branch instead of gh-pages?

**Comment by zaridan** [comment]
Thank you for the input on content. I agree we shouldn't need a page for everything, and will run with just those two you mentioned.

And thanks for the suggestion on then PR to the other branch, for sure, I wasn't paying attention there. Please close this PR and I'll do another.

**Comment by edswf1** [comment]
> Thank you for the input on content. I agree we shouldn't need a page for everything, and will run with just those two you mentioned.
> 
> And thanks for the suggestion on then PR to the other branch, for sure, I wasn't paying attention there. Please close this PR and I'll do another.

not your fault at all, i'm still new to the github game and just learned it is better to keep things isolated 😄

**Pull request closed without merging**
